name: Node.js Fullstack CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd kal2go-backend && npm ci
      - run: cd kal2go-backend && npm test
      - run: cd kal2go-backend && node index.js # הרצת ה-Backend

  frontend:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd kal2go-shop && npm ci
      - run: cd kal2go-shop && npm run build --if-present # בנייה
      - run: cd kal2go-shop && npm start # הרצת ה-Frontend
